### PR TITLE
Some more fixes

### PR DESCRIPTION
**Pull request by krnowak**
So, I have been looking at the `ostree_avahi_service_build_repo_finder_result` function. I think I will modify it to return `NULL` if any field of `v`, `rb`, `ri` and `st` are missing. Also, [this block](https://github.com/kinvolk/ostree/blob/5b2fb1ed27666bd9a29b81076dd7e7e9d4ac9618/src/libostree/ostree-repo-finder-avahi.c#L479-#L481) needs fixing - it will trip an assertion I just added. How should I do it? Just try to fetch the latest commit in this ref from the repo?

### CODE REVIEW

**Comment by pwithnall** [comment]
> Also, this block needs fixing - it will trip an assertion I just added. How should I do it? Just try to fetch the latest commit in this ref from the repo?

You need to add something to that block which downloads the `summary` file for the remote, and reads the ref checksums from it. I thought about having that code in `ostree_repo_find_remotes_async()` instead, but I think it makes more sense to be in the individual repo finders, since otherwise `ostree_repo_finder_resolve_async()` is useless by itself. There should be a convenience method in libostree already for downloading (and caching, which is very important) a `summary` file.

**Comment by krnowak** [comment]
Just added a commit that adds fetching of the summary when discovering the servers over LAN. I haven't tested it at all, but at least it compiles. Two notes:

- fetching the summary likely defeats the purpose of sending summary timestamp over the TXT records.
- the `ostree_repo_remote_fetch_summary_with_options` will unlikely work - it seems to me that this code expects the remote to be stored in the repository, which it is not in our case. Maybe ostree will need further changes there.

**Comment by pwithnall** [comment]
> fetching the summary likely defeats the purpose of sending summary timestamp over the TXT records.

At the moment, yes; but there is scope for adding an `If-Modified-Since` header in the request for the `summary`, using the timestamp from the TXT record, to avoid downloading the summary if it hasn’t been modified. Or comparing the timestamp against that of a locally cached `summary` to avoid the request at all. Those are future optimisations though.

> the ostree_repo_remote_fetch_summary_with_options will unlikely work - it seems to me that this code expects the remote to be stored in the repository, which it is not in our case. Maybe ostree will need further changes there.

Likely, yes.

**Comment by pwithnall** [comment]
I’ve merged this into my branch, thanks. I removed the `OstreeRepoFinderAvahi` API changes, since I’ve added a `parent_repo` argument to `repo_finder.resolve_async` in the meantime.

**Comment by krnowak** [comment]
Updated with some more fixes. Currently `ostree find-remotes --pull os/eos/amd64/master` can find the update on the LAN and probably pulls the refs, but it is suspiciously blazingly fast, even taking into account that both LAN client and LAN server are VMs on my machine. I still need to figure out how to deploy the fetched ref (`ostree admin deploy os/eos/amd64/master` will not work as it resolves `os/eos/amd64/master` to the already deployed commit; I need to figure out how to tell ostree to deploy a specific commit; might not be possible with command line currently).

**Comment by pwithnall** [comment]
I’ve squashed the latest round of fixes into my branch, except for your commit to disable the Avahi unit tests, which I kept separate until we work out what the linking problem is (I didn’t take a close look due to lack of time; I’m happy for us to carry the patch for some time while we work on more important things).

**Comment by krnowak** [comment]
Updated.

**Comment by pwithnall** [comment]
> Updated.

Cherry picked into both of my branches, thanks. I’ll squash it in properly later.

**Pull request closed without merging**
